### ISSUE TITLE
Can't cast Jwk to RSAPublicKey

### ISSUE THREAD

**Issue by Copy33** [auth0/jwks-rsa-java#18]
Using UrlJwkProvider here's my code.
```
JwkProvider provider = new UrlJwkProvider(url);
Jwk jwk = provider.get(keyId);
RSAPublicKey publicKey = (RSAPublicKey) jwk;
```
The reason I need the conversion is to use [java-jwt library](https://github.com/auth0/java-jwt) to be able to do this:
```
Algorithm algorithm = Algorithm.RSA256(publicKey, null);
JWTVerifier verifier = JWT.require(algorithm)
                       .withIssuer("auth0")
                       .build();
DecodedJWT jwt = verifier.verify(mToken);
```
I am getting an error saying
com.auth0.jwk.Jwk cannot be cast to java.security.interfaces.RSAPublicKey 
even though it's in their documentation and they pointed me to this library (all under auth0).
Also
```
RSAPublicKey publicKey = jwk.getPublicKey();
```
doesn't work on Android because of missing decodebase64 error.
Any ideas?

**Comment by lbalmaceda** [comment]
- The reason you're getting that exception is because JWK is not a PublicKey. If you [check the library repo](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/Jwk.java#L166) you'd notice that you must call `jwk.getPublicKey()` in order to obtain it.
- I'd also suggest you try creating a new instance of `Algorithm` using the other method as shown [here](https://github.com/auth0/java-jwt#using-a-keyprovider).
- This library is using the apache commons lib which is not ready for Android. We will discuss internally if we should add support to Android.

**Comment by eschoenawa** [comment]
> This library is using the apache commons lib which is not ready for Android. We will discuss internally if we should add support to Android.

Is there an alternative for Android by now?

**Comment by lbalmaceda** [comment]
Android SDK has it's own `android.util.Base64` class. Since the JDK it uses depends on the Android platform version, some JDK8 classes like [Base64](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) are only available on a subset of android versions. This library is not meant for android but you could emulate the behavior using the util class I mentioned.
