### ISSUE TITLE
Provide a Jwk constructor from a map of values

### ISSUE THREAD

**Issue by underscorenico** [auth0/jwks-rsa-java#35]
I am using this project but I would really need a way to create a `Jwk` from a Json object. 

Since there already exists a (package private) method `fromValues` in the `Jwk` class that takes a `Map` as parameter, making it `public` could be an easy way for providing an static method for creation from a json.

**Comment by lbalmaceda** [comment]
@underscorenico What's your use case? The URL provider already supports both local (files) or remote sources.

**Comment by underscorenico** [comment]
We have implemented our own methods for retrieving the JWKs because we are in an async context (Vert.x) and we cannot use blocking calls in a provider.
(Un abrazo desde Francia :) )

**Comment by lbalmaceda** [comment]
👋 while it can be done I think it's messy to have a public method accepting just a Map of claims and creating something inside. If that happens I rather have a builder class that accepts any possible param, validating the input when required, and ends up calling that internal method. i.e.

```java
Jwk jwk = new JwkBuilder()
     .withKid("")
     .withKty()
     .build();
```

However, going back to your use case I understand that you want to avoid calling `url.openConnection()` as is being [done here](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/UrlJwkProvider.java#L92) (why not creating a new thread?). If that's true then none of the providers included in this library will work for you, because they are based on that same URL provider I originally mentioned. Furthermore, you're not going to take any advantage of the cache and bucket leak features. If you ask me, since you're not using using this features it's more straightforward to just take the `Jwk.java` class with you (MIT) and modify it to your needs, or even construct the Public Key from a constant or file.
