### ISSUE TITLE
Distinct between connection issues and attacks in UrlJwkProvider

### ISSUE THREAD

**Issue by JoergAdler** [auth0/jwks-rsa-java#79]
# Describe the problem you'd like to have solved
Hi there in UrlJwkProvider a SigningKeyNotFoundException is thrown in the method "Jwk get(String keyId)" for two different reasons:

1. If in getAll()-> getJwks() the connection  to the location of the JWK fails. Which is an serious issue for operation of the service, as most likely all token could not be verified)
2. If the KeyId in the token could not be found. (most likely if an attacker sets an arbitrary key id in the token)

### Describe the ideal solution

Please make it possible to distinct between these two cases with a proper exception being thrown. To not break any existing code, which is calling the methods, the new exception should be a child class of SigningKeyNotFoundException or a RuntimeException.

## Alternatives and current work-arounds

A current workaround will be to look at the cause of the exception, which is a fragile, as one has to know which specific connection issues could occur and that there is no other place, where such an exception could be thrown.

An alternative of the approach above will be to change the return type of "Jwk get(String keyId)" to "Optional<Jwk> get(String keyId)" that there is a distinction between the the more common case, where a key with the wrong keyId is requested an an exceptional connection problem. This will involve more rework.

Thank you for considering this change.

**Comment by lbalmaceda** [comment]
For the first one yes, it might make sense to tell there was an IO error or network timeout. But the most common scenario for it would be a configuration error (e.g. setting the wrong URI). For the second one, I think the current exception describes the intention correctly.

I'll evaluate it with the java team.

**Comment by JoergAdler** [comment]
Hi. In my case, there was the right url, it was only not available due to some connection problems, which can occur at any time when the service is running.

**Comment by lbalmaceda** [comment]
Let's keep this one open :D

**Comment by lbalmaceda** [comment]
Tracking internally `SDK-1658`

**Comment by lbalmaceda** [comment]
@JoergAdler I was reviewing the library code. The "network error" scenario would always be attached to an `IOException` cause. You mentioned something around this already:

>as one has to know which specific connection issues could occur

It really doesn't matter much what the cause of the network issue was. It was impossible for the library to fetch the JWKS from the network. Is there any scenario where you could do anything other than retrying the request until it succeeds?

I can add a new exception class like "NetworkException" to simplify capturing this scenario. But it sounds a lot like what the IOException already represents, and you're already checking the cause to handle that. What about adding a getter for a property like "isNetworkError()" that checks if the cause was an `IOException`? That would save you from checking the cause manually and us from adding yet another exception class to the library (already has 4).

Then, if we evaluate the remaining two error scenarios, we have a JSON parsing exception, typically happening when the content is invalid. There's no action you can take to recover from that. And the other one is when everything worked fine but the key is not present in the array. Which is already what the exception means.

**Comment by lbalmaceda** [comment]
We haven't heard back from you. I've added docs explaining how to capture these scenarios and handle them, depending on your use case. I hope that helps. Cheers

**Comment by lbalmaceda** [comment]
> At the moment we have to treat both scenarios the same, which leads to infrastructure alarms if receiving wrong tokens :-(

The only place in the code where the library could throw an exception with an `IOException` cause is when making the request [here](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/UrlJwkProvider.java#L112). I thought that checking the cause was OK. It's still not clear to me what you are proposing. Wrapping that scenario in its own "network exception" class?

**Comment by JoergAdler** [comment]
Wrapping it into a child class of SigningKeyNotFound will be one of the proposed solutions (from above). So existing code will not break and one can catch this new exception if needed without looking at the cause.

As I mentioned: a more cleaner version in my opinion would be to change the return type of the method to optional. The more common case „there is no key for that id“ would than be covered by optional.empty and leaving the exceptional case of network errors to the exceptions.

**Comment by lbalmaceda** [comment]
@JoergAdler does this work for you? https://github.com/auth0/jwks-rsa-java/pull/89

**Comment by JoergAdler** [comment]
Cool. Thanks a lot 👍🏻😊
